# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/martilda
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-{{ .Branch }}
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/martilda/node_modules
            - ~/martilda/dist
  deploy:
    working_directory: ~/martilda
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
        keys:
          - npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - npm-{{ .Branch }}
      - run:
          name: Install Dependency
          command: npm install
      - run:
        name: deploy
        command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN
workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
